// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9l51jnteTUH2e5xeSPa3_eFliDxyl--c',
    appId: '1:606005521540:web:5e4d55ae84b7ac2c72e6d1',
    messagingSenderId: '606005521540',
    projectId: 'messageme-app-a33a1',
    authDomain: 'messageme-app-a33a1.firebaseapp.com',
    storageBucket: 'messageme-app-a33a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGQV_0LUB-5aQzAgAMJpbT5nVY3VSwA6c',
    appId: '1:606005521540:android:b4068f137820cd8f72e6d1',
    messagingSenderId: '606005521540',
    projectId: 'messageme-app-a33a1',
    storageBucket: 'messageme-app-a33a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxoj5_2Tv3jQFGjbzfOh5M80YyfW_Kb-4',
    appId: '1:606005521540:ios:404a55fc68402f9072e6d1',
    messagingSenderId: '606005521540',
    projectId: 'messageme-app-a33a1',
    storageBucket: 'messageme-app-a33a1.appspot.com',
    iosClientId: '606005521540-ajk6gjhss6jm5ad04ubq0i6mq0srg2bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxoj5_2Tv3jQFGjbzfOh5M80YyfW_Kb-4',
    appId: '1:606005521540:ios:404a55fc68402f9072e6d1',
    messagingSenderId: '606005521540',
    projectId: 'messageme-app-a33a1',
    storageBucket: 'messageme-app-a33a1.appspot.com',
    iosClientId: '606005521540-ajk6gjhss6jm5ad04ubq0i6mq0srg2bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
